version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile.backend
        networks:
            - my-app
        volumes:
            - ./:/var/www
        environment:
            - APP_ENV=local
        ports:
            - "8000:8000"
        depends_on:
            - db
        command: ["sh", "-c", "composer install && php artisan serve --host=0.0.0.0 --port=8000"]
        


    frontend:
        build:
            context: .
            dockerfile: Dockerfile.frontend
        networks:
            - my-app
        volumes:
                - ./:/var/www
                - .:/var/www/html:cached
                - /var/www/html/vendor
                - /var/www/node_modules
        ports:
            - "5173:5173"

    db:
        image: mysql:8.0
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: xshop
            MYSQL_ROOT_PASSWORD: password  # Must match DB_PASSWORD in .env
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - my-app

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: myphpmyadmin
        restart: unless-stopped
        ports:
            - "8080:80"
        environment:
            PMA_HOST: db
            PMA_USER: root
            PMA_PASSWORD: password
        depends_on:
            - db
        networks:
            - my-app
volumes:
    db_data:

networks:
    my-app:
        driver: bridge
