FROM node:20

WORKDIR /var/www

# First copy only package files
COPY package.json package-lock.json* ./


RUN npm install

# Copy the rest of the files
COPY . .

EXPOSE 5173
CMD ["npm", "run", "dev"]
